issuer: https://token.actions.githubusercontent.com
subject: repo:imjasonh/octo-sts-js:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: imjasonh/octo-sts-js/.github/workflows/use-action.yaml@refs/heads/main

permissions:
  pull_requests: write
  workflows: write
