issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/octo-sts-js:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/octo-sts-js/.github/workflows/use-action.yaml@refs/heads/main

permissions:
  contents: read
  issues: write
