name: Use Action

on:
  push:
    branches: ['main']

permissions:
  id-token: write # Needed to federate with octo-sts

jobs:
  use-action:
    name: Use Action
    runs-on: ubuntu-latest

    steps:
      - id: octo-sts
        uses: chainguard-dev/octo-sts-js@main
        with:
          scope: chainguard-dev/octo-sts-js
          identity: use-action

      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: gh issue create --title "Use Action" --body "This issue was created using an Octo STS token"
